"$schema" = "./node_modules/wrangler/config-schema.json"

name = "giaydephuongnho"
pages_build_output_dir = "public"
compatibility_date = "2026-05-31"
compatibility_flags = ["nodejs_compat"]

[vars]
PORT = "3000"
APP_URL = "https://giaydephuongnho.pages.dev"
GOOGLE_CALLBACK_URL = "https://giaydephuongnho.pages.dev/api/auth/google/callback"
